### ISSUE TITLE
Error when trying to add a new dependency to the project using pnpm

### ISSUE THREAD

**Issue by henrique-leme** [woovibr/woovi-playground#101]
# Bug
while trying to add the dependency cpy-cli, i've got the follow error:
![image](https://github.com/sibelius/relay-workshop/assets/70873562/dc5ef290-34eb-4e38-b7d7-33860cf70822)

this happens both on the server folder and the web folder, when I run the follow command: pnpm add -D cpy-cli  

## Environment info
Windows 10
Node v21.6.1
pnpm v9.1.1
npm v10.5.0

**Comment by sibelius** [comment]
how did you fixed it?

**Comment by henrique-leme** [comment]
I didn't actually fixed it, but I closed it cause I doesn't look like a bug, maybe something around permissions, I'm gonna investigate it later today, because I tried to install the same dependency in another project and it worked.

Maybe Eckzzo can clarify it to me

**Comment by dantas15** [comment]
alternatively, you can set your own `link-workspace-packages` to true in your `.npmrc` file
