### ISSUE TITLE
Migrate to graphql-yoga

### ISSUE THREAD

**Issue by fersilva16** [woovibr/woovi-playground#20]
- [ ] Migrate GraphQL Implementation to GraphQL Helix

https://the-guild.dev/graphql/yoga-server

**Comment by sibelius** [comment]
not sure about it

**Comment by daniloab** [comment]
> * [ ]  Migrate GraphQL Implementation to GraphQL Helix
> 
> [the-guild.dev/graphql/yoga-server](https://the-guild.dev/graphql/yoga-server)

helix or youga?

**Comment by edumaciel10** [comment]
- const x pros?
